companies:
  - company_key: 1
    cik: "0000320193"
    ticker: AAPL
    company_name: Apple Inc.
    sector: Technology
  - company_key: 2
    cik: "0000789019"
    ticker: MSFT
    company_name: Microsoft Corporation
    sector: Technology
  - company_key: 3
    cik: "0001652044"
    ticker: GOOGL
    company_name: Alphabet Inc.
    sector: Communication Services
  - company_key: 4
    cik: "0001018724"
    ticker: AMZN
    company_name: Amazon.com, Inc.
    sector: Consumer Discretionary
  - company_key: 5
    cik: "0001326801"
    ticker: META
    company_name: Meta Platforms, Inc.
    sector: Communication Services
  - company_key: 6
    cik: "0001045810"
    ticker: NVDA
    company_name: NVIDIA Corporation
    sector: Technology
